name: Fast checkout
description: Uses prebaked repo on self-hosted runners
inputs:
  fetch-depth:
    description: How many commits of history to fetch (0 = all history)
    required: false
    default: 1
    type: number

runs:
  using: composite
  steps:
    - id: choose-commit
      shell: bash
      # The special case is necessary to check out the pull request if this run
      # was triggered via a `pull_request_target` event.
      run: |
        if [ '${{ github.event_name }}' == pull_request_target ]; then
          echo "commit=${{ github.event.pull_request.head.sha }}" | tee -a $GITHUB_OUTPUT
        else
          echo "commit=$GITHUB_SHA" | tee -a $GITHUB_OUTPUT
        fi

    - if: ${{ runner.environment != 'self-hosted' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.choose-commit.outputs.commit }}
        fetch-depth: ${{ inputs.fetch-depth }}

    # Use prebaked repo on self-hosted runners
    - if: ${{ runner.environment == 'self-hosted' && inputs.fetch-depth != 0 }}
      shell: bash
      run: git fetch --depth=${{ inputs.fetch-depth }} origin ${{ steps.choose-commit.outputs.commit }}
    - if: ${{ runner.environment == 'self-hosted' && inputs.fetch-depth == 0 }}
      shell: bash
      run: git fetch origin ${{ steps.choose-commit.outputs.commit }}
    - if: ${{ runner.environment == 'self-hosted' }}
      shell: bash
      # Same as `git switch --detach FETCH_HEAD`, but fixes up dirty working
      # trees, in case the runner image was baked with a dirty working tree.
      run: |
        git switch --detach
        git reset --hard FETCH_HEAD
