name: Fast checkout
description: Uses prebaked repo on self-hosted runners
inputs:
  fetch-depth:
    description: How many commits of history to fetch (0 = all history)
    required: false
    default: 1
    type: number

runs:
  using: composite
  steps:
    - id: choose-commit
      shell: bash
      # The special case is necessary to check out the pull request if this run
      # was triggered via a `pull_request_target` event.
      run: |
        if [ '${{ github.event_name }}' == pull_request_target ]; then
          echo "commit=${{ github.event.pull_request.head.sha }}" | tee -a $GITHUB_OUTPUT
        else
          echo "commit=$GITHUB_SHA" | tee -a $GITHUB_OUTPUT
        fi

    - uses: actions/checkout@v6
      with:
        ref: ${{ steps.choose-commit.outputs.commit }}
        fetch-depth: ${{ inputs.fetch-depth }}
        # This is necessary to check out pull requests for `pull_request_target` actions,
        # which are used for things like the WPT update job and the try label.
        allow-unsafe-pr-checkout: true
        clean: ${{ runner.environment != 'self-hosted' }}
