#!/usr/bin/env zsh
set -euo pipefail -o bsdecho -o shwordsplit
action=$1; shift

case "$action" in
(deploy)
    for host; do
        ./deploy -s "$host".servo.org "$host"
    done
    for host; do
        printf '>>> %s\n' https://"$host".servo.org
    done
    ;;
(read)
    for host; do
        mkdir -p -- "$host"
        rsync root@"$host".servo.org:/config/monitor/{.env,monitor.toml} "$host"/
    done
    ;;
(write)
    for host; do
        rsync "$host"/{.env,monitor.toml} root@"$host".servo.org:/config/monitor/
    done
    ;;
(restart-monitor)
    for host; do
        ssh root@"$host".servo.org systemctl restart monitor
    done
    for host; do
        printf '>>> %s\n' https://"$host".servo.org
    done
    ;;
(restart-queue)
    for host; do
        ssh root@"$host".servo.org systemctl restart queue
    done
    for host; do
        printf '>>> %s\n' https://"$host".servo.org/queue/
    done
    ;;
(run)
    hosts=
    for arg; do
        case "$arg" in
        (--)
            shift
            break
            ;;
        (*)
            hosts="$hosts $arg"
            shift
            ;;
        esac
    done
    for host in $hosts; do
        ssh root@"$host".servo.org -- "$@"
    done
    ;;
(mosh)
    host=$1; shift
    mosh root@"$host".servo.org -- "$@"
    ;;
(logs)
    mosh root@"$1".servo.org tmux new 'journalctl -af'
    ;;
(htop)
    mosh root@"$1".servo.org tmux new 'htop'
    ;;
(*)
    >&2 echo 'usage: ./do <deploy|read|write|restart-monitor|restart-queue|run|mosh|logs|htop> [args ...]'
    exit 1
    ;;
esac
